import type { Chapter } from "./types";

/**
 * The chapters, in the exact order the story should be read.
 * Text is intentionally sparse — the photos and the silence between
 * lines carry the emotion. Required verbatim passages (Doctor, Engineer,
 * Together, Achievement, Golden Promise, Final) are preserved word-for-word.
 *
 * Chapter numbers are derived from array order (see the map at the bottom),
 * so inserting a new chapter never means renumbering the rest by hand.
 */
const orderedChapters: Omit<Chapter, "index">[] = [
  {
    id: "childhood",
    emoji: "👶",
    icon: "Baby",
    eyebrow: "Once upon a time",
    title: "Before We Knew Each Other",
    subtitle: "Two children. Two different lives.",
    narrative: [
      "Once upon a time, two children were growing up under the same sky — completely unaware that one day, their paths would become one.",
      "A curly-haired boy by the Bosphorus. A bright-eyed girl a world away.",
      "Every memory before us was quietly leading us to each other.",
    ],
    mood: {
      gradient: "from-chocolate-100 via-warm-100 to-olive-100",
      accent: "#c9a24e",
      scheme: "light",
    },
    slots: 6,
    inMenu: true,
  },
  {
    id: "eyes",
    emoji: "👀",
    icon: "Eye",
    eyebrow: "A closer look",
    title: "Our Eyes",
    subtitle: "His. Hers. Then — ours.",
    narrative: ["His eyes.", "Her eyes.", "And the quiet moment they finally met."],
    mood: {
      gradient: "from-navy-950 via-navy-900 to-black",
      accent: "#6b7dfb",
      scheme: "dark",
    },
    slots: 3,
    inMenu: true,
  },
  {
    id: "beginning",
    emoji: "🤍",
    icon: "Sparkle",
    eyebrow: "24 August 2023",
    title: "The Beginning",
    subtitle: "The day everything changed.",
    narrative: [
      "Years passed. Life changed. Cities, exams, ordinary Tuesdays.",
      "And then — one date that would never feel ordinary again.",
      "24 August 2023. The moment two separate stories became one.",
    ],
    mood: {
      gradient: "from-steel-100 via-warm-50 to-royal-100",
      accent: "#4655ef",
      scheme: "light",
    },
    slots: 4,
    inMenu: true,
  },
  {
    id: "first-picture",
    emoji: "📸",
    icon: "Camera",
    eyebrow: "The very first frame",
    title: "First Picture Together",
    subtitle: "Proof that this was real.",
    narrative: [
      "The first photograph of us together.",
      "A little nervous. A little unsure of where to look.",
      "But already — unmistakably — home.",
    ],
    mood: {
      gradient: "from-warm-50 via-warm-100 to-steel-100",
      accent: "#4d7599",
      scheme: "light",
    },
    slots: 4,
    inMenu: true,
  },
  {
    id: "everyday",
    emoji: "🌸",
    icon: "Flower2",
    eyebrow: "The ordinary magic",
    title: "Everyday Moments",
    subtitle: "The small things that were never small.",
    narrative: [
      "Not every memory is a grand occasion.",
      "Most of ours live in the in-between — a look across a room, a message at midnight, a laugh that lasted too long.",
      "These are the moments we would live again a thousand times.",
    ],
    mood: {
      gradient: "from-olive-100 via-warm-50 to-forest-100",
      accent: "#4e9c66",
      scheme: "light",
    },
    slots: 8,
    inMenu: true,
  },
  {
    id: "hand-in-hand",
    emoji: "🤝",
    icon: "Hand",
    eyebrow: "Connection",
    title: "Hand in Hand",
    subtitle: "Not about objects — about connection.",
    narrative: [
      "Before forever became a promise, it began with a simple touch.",
      "Two wrists wearing the same beads. Two spoons that somehow made a heart.",
      "Every hand tells a story of trust, comfort, support — and love.",
    ],
    mood: {
      gradient: "from-chocolate-900 via-navy-950 to-black",
      accent: "#d8a24e",
      scheme: "dark",
    },
    slots: 0,
    inMenu: true,
  },
  {
    id: "trips",
    emoji: "🌊",
    icon: "Waves",
    eyebrow: "Places we wandered",
    title: "Trips",
    subtitle: "New horizons, same hand to hold.",
    narrative: [
      "We went looking for the sea, for streets we'd never walked, for skies we'd never seen.",
      "But the truth is — the destination never mattered much.",
      "As long as we arrived together.",
    ],
    mood: {
      gradient: "from-steel-200 via-steel-100 to-navy-200",
      accent: "#3c5d7f",
      scheme: "light",
    },
    slots: 6,
    inMenu: true,
  },
  {
    id: "ramadan",
    emoji: "🌙",
    icon: "Moon",
    eyebrow: "Blessed nights",
    title: "Ramadan",
    subtitle: "A quieter, warmer kind of light.",
    narrative: [
      "Lanterns in the window. A calm that settles over everything.",
      "Ramadan gave our story a softer glow — gratitude, patience, and prayers we quietly made for one another.",
      "Some of our warmest memories were written under this crescent moon.",
    ],
    mood: {
      gradient: "from-navy-900 via-plum-900 to-navy-950",
      accent: "#cfa24e",
      scheme: "dark",
    },
    slots: 5,
    inMenu: true,
  },
  {
    id: "gifts",
    emoji: "🎁",
    icon: "Gift",
    eyebrow: "Little treasures",
    title: "Gifts",
    subtitle: "Not the price — the thought behind it.",
    narrative: [
      "Every gift was a sentence in a language only we speak.",
      "Wrapped carefully, chosen slowly, given with a heart that was paying attention.",
      "And one of them — gold, and glowing — deserves its own light.",
    ],
    mood: {
      gradient: "from-chocolate-100 via-gold-100 to-warm-100",
      accent: "#cfa24e",
      scheme: "light",
    },
    slots: 5,
    inMenu: true,
  },
  {
    id: "golden-promise",
    emoji: "💍",
    icon: "Gem",
    eyebrow: "A promise in gold",
    title: "Our First Golden Promise",
    subtitle: "The first gift of forever.",
    narrative: [
      "The first gold Boody ever gave Manonty — a deep green stone, haloed in light, on a chain of warm gold.",
      "Gold has value because it lasts. But this gift became priceless because of the love behind it.",
      "It wasn't just the first piece of gold. It was the first promise I could hold in my hands.",
    ],
    mood: {
      gradient: "from-black via-navy-950 to-chocolate-900",
      accent: "#cfa24e",
      scheme: "dark",
    },
    slots: 0,
    inMenu: true,
  },
  {
    id: "love",
    emoji: "💌",
    icon: "Mail",
    eyebrow: "In our own words",
    title: "Love",
    subtitle: "Everything we never had to explain.",
    narrative: [
      "Love, for us, was rarely loud.",
      "It was reliable. Patient. The kind that shows up on the hard days and stays for the ordinary ones.",
      "This chapter is simply — us.",
    ],
    mood: {
      gradient: "from-burgundy-100 via-warm-50 to-plum-100",
      accent: "#b7414f",
      scheme: "light",
    },
    slots: 6,
    inMenu: true,
  },
  {
    id: "journey-together",
    emoji: "💞",
    icon: "Images",
    eyebrow: "The heart of it all",
    title: "Our Journey Together",
    subtitle: "Some people measure time in years. We measure it in moments.",
    narrative: [
      "Every photo here is a real moment we shared — laughter, peace, love.",
      "Not a gallery. A memory book, one page at a time.",
      "Every picture tells a story. Together, they became our forever.",
    ],
    mood: {
      gradient: "from-warm-100 via-warm-50 to-gold-100",
      accent: "#cfa24e",
      scheme: "light",
    },
    slots: 0,
    inMenu: true,
  },
  {
    id: "doctor",
    emoji: "👩🏻‍⚕️",
    icon: "Stethoscope",
    eyebrow: "Manonty",
    title: "The Doctor",
    subtitle: "She heals people with science and kindness.",
    narrative: [
      "She chose medicine to heal people.",
      "And without trying…",
      "she healed my heart too.",
    ],
    mood: {
      gradient: "from-steel-50 via-warm-50 to-royal-100",
      accent: "#4655ef",
      scheme: "light",
    },
    slots: 4,
    inMenu: true,
  },
  {
    id: "engineer",
    emoji: "👷🏻‍♂️",
    icon: "Ruler",
    eyebrow: "Boody",
    title: "The Engineer",
    subtitle: "I build bridges, buildings, dreams.",
    narrative: [
      "Engineering taught me how to build structures.",
      "Life taught me that the most beautiful thing I'll ever build",
      "is our future.",
    ],
    mood: {
      gradient: "from-navy-950 via-navy-900 to-steel-900",
      accent: "#6b7dfb",
      scheme: "dark",
    },
    slots: 4,
    inMenu: true,
  },
  {
    id: "together",
    emoji: "🤝",
    icon: "HeartHandshake",
    eyebrow: "Two worlds, one design",
    title: "Together",
    subtitle: "Where medicine and engineering become one.",
    narrative: [
      "Blueprint lines slow, and soften, and begin to beat.",
      "Buildings round into hearts. A stethoscope traces the same curve as a bridge.",
      "Two disciplines, two people — building one life.",
    ],
    mood: {
      gradient: "from-navy-900 via-royal-900 to-burgundy-900",
      accent: "#94a6ff",
      scheme: "dark",
    },
    slots: 0,
    inMenu: true,
  },
  {
    id: "achievement",
    emoji: "🎓",
    icon: "GraduationCap",
    eyebrow: "American Diploma · Mathematics",
    title: "We Succeeded Together",
    subtitle: "We didn't only dream together.",
    narrative: [
      "Long nights. Practice tests. Encouraging each other when the numbers refused to make sense.",
      "We didn't only dream together.",
      "We succeeded together.",
    ],
    mood: {
      gradient: "from-navy-900 via-navy-800 to-gold-600",
      accent: "#cfa24e",
      scheme: "dark",
    },
    slots: 0,
    inMenu: true,
  },
  {
    id: "dictionary",
    emoji: "📖",
    icon: "BookHeart",
    eyebrow: "A language of two",
    title: "Our Dictionary",
    subtitle: "To everyone else, they're just words.",
    narrative: [
      "Every couple invents a small private language.",
      "A handful of words that mean nothing to the world — and everything to us.",
    ],
    mood: {
      gradient: "from-warm-100 via-warm-50 to-steel-100",
      accent: "#4655ef",
      scheme: "light",
    },
    slots: 0,
    inMenu: true,
  },
  {
    id: "journey",
    emoji: "❤️",
    icon: "Route",
    eyebrow: "Milestone by milestone",
    title: "Our Journey",
    subtitle: "Everything, in the order it happened.",
    narrative: [
      "A story is really just a series of moments, held together by love.",
      "Here is ours — the way it unfolded.",
    ],
    mood: {
      gradient: "from-royal-100 via-warm-50 to-burgundy-100",
      accent: "#4655ef",
      scheme: "light",
    },
    slots: 0,
    inMenu: true,
  },
  {
    id: "today",
    emoji: "✨",
    icon: "Sun",
    eyebrow: "Right now",
    title: "Today",
    subtitle: "Still writing. Still us.",
    narrative: [
      "And here we are.",
      "Older, softer, more certain of each other than ever.",
      "The story isn't finished — it's simply still being lived.",
    ],
    mood: {
      gradient: "from-warm-50 via-royal-100 to-steel-100",
      accent: "#4655ef",
      scheme: "light",
    },
    slots: 6,
    inMenu: true,
  },
];

/** Chapter numbers are assigned from order — insert anywhere, no renumbering. */
export const chapters: Chapter[] = orderedChapters.map((c, i) => ({
  ...c,
  index: i + 1,
}));

export const chapterById = Object.fromEntries(
  chapters.map((c) => [c.id, c]),
) as Record<Chapter["id"], Chapter>;

export const menuChapters = chapters.filter((c) => c.inMenu);
